name: Build and release

# Create release on versioned tags
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            arch: linux-x64
          - os: windows-latest
            arch: windows-x64
          - os: macos-latest
            arch: macos-aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build binary
        run: |
          cargo build --release --verbose
          mkdir -p dist
          if [[ "${{ matrix.platform.os }}" == "windows-x64" ]]; then
            mv target/release/*.exe dist/myucel-${{ matrix.platform.arch }}.exe
          else
            mv target/release/myucel dist/myucel-${{ matrix.platform.arch }}
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.arch }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
